version: "3"
services:
  api:
    working_dir: /usr/src/api
    build: ./api
    restart: always
    image: deadly-banjo-api:latest
    container_name: deadly-banjo-api
    volumes:
      - ./api:/usr/src/api
    environment:
      - NODE_ENV=development
      - PORT=8088
    ports:
      - 8088:8088
    command: npm start
    env_file:
      - .env
  db:
    image: postgres:10
    restart: always
    container_name: deadly-banjo-db
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: db
      PGDATA: /tmp
    ports:
      - 5432:5432
